spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/quotation
    username: springstudent
    password: springstudent
    driver-class-name: org.mariadb.jdbc.Driver
  hikari:
    minimum-idle: 5
    maximum-pool-size: 20
    idle-timeout: 30000
    max-lifetime: 1800000
    connection-timeout: 30000
    auto-commit: true
    jpa:
      hibernate:
        ddl-auto: create
      properties:
        hibernate:
          dialect: org.hibernate.dialect.MariaDBDialect